baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "Don't worry, be happy!"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""


[params]
  author = "TruthSeeker"
  description = ""
[params.search]
  enable = true
[params.darkmode]
  enable = false